### ISSUE TITLE
How is this module different than the existing JSON::Schema?

### ISSUE THREAD

**Issue by perlancar** [zigorou/perl-JSV#33]
Perhaps mention this in your POD (in See Also section)?

**Comment by Relequestual** [comment]
It looks like it only supports draft 4, while JSON::Schema supports draft 3 only (and not fully).

*checks out this repo to run the tests!*

**Comment by zigorou** [comment]
@perlancar. @Relequestual 

Thanks your suggestion.
Differences from JSON::Schema to JSV is few points.

* JSV only supports draft-04, but JSON::Schema only supports draft-03.
* JSV considers performance, for example, JSV supports JSON References and JSV expects preloading depended schemas. But JSON::Schema only supports dynamic loading using LWP each time. It is not usable on production.

Now JSV does not have enough document. I'll add more information including this.
Thanks.
