### ISSUE TITLE
json-schema test suite information

### ISSUE THREAD

**Issue by Relequestual** [zigorou/perl-JSV#34]
Hey Toru. From the looks of your recent work on this module, it looks like you're converting the tests from the json-schema test suite to perl tests. Is this correct? How do I run these tests for your module?

I am working on a module that will allow you to run all of the tests from the test suite without the need to write a new perl test for each one. You define how your module does validation, which draft, and any tests to exclude, and it will run all the tests from the json files.

I'll let you know as soon as it is ready! As I'm doing this as part of my day job, I expect it won't be too far in the future.

**Comment by zigorou** [comment]
@Relequestual 

At first, I cannot write English well. Sorry.

> Hey Toru. From the looks of your recent work on this module, it looks like you're converting the tests from the json-schema test suite to perl tests. Is this correct? How do I run these tests for your module?

Please use `Test::JSV::Suite`. How to use it, look test script. ([/master/t/draft4/suite/additionalItems.t](https://github.com/zigorou/perl-JSV/blob/master/t/draft4/suite/additionalItems.t)

> I am working on a module that will allow you to run all of the tests from the test suite without the need to write a new perl test for each one.

Do you know that JSV supports loose_type mode?
The loose_type mode doesn't support all test cases in JSON-Schema-Test-Suite.
So I made separated tests by each cases.

Therefore if this module only supports strict mode, running all test cases in test suite is able in one file.
 
> I'll let you know as soon as it is ready! As I'm doing this as part of my day job, I expect it won't be too far in the future.

I cannot understand why do you want to hurry up, but I'll look it when you send PR.
Regards.
